#!/usr/bin/env zsh
set -euo pipefail

ZSHRC_FILE="${1:-$HOME/.zshrc}"
IMAGE_NAME="${NEMESIS_DOCKER_IMAGE:-patrickirwinoxford/docker_nemesis}"
SCRIPT_DIR="${0:A:h}"
EXECUTABLES_FILE="${NEMESIS_EXECUTABLES_FILE:-$SCRIPT_DIR/nemesis_executables.txt}"
START_MARKER="# >>> NEMESIS docker aliases >>>"
END_MARKER="# <<< NEMESIS docker aliases <<<"

if [[ ! -f "$EXECUTABLES_FILE" ]]; then
  print -u2 "Executable list not found: $EXECUTABLES_FILE"
  exit 1
fi

executables=()
while IFS= read -r executable; do
  executable="${executable#"${executable%%[![:space:]]*}"}"
  executable="${executable%"${executable##*[![:space:]]}"}"

  if [[ -z "$executable" || "$executable" == \#* ]]; then
    continue
  fi

  executables+=("$executable")
done < "$EXECUTABLES_FILE"

if ((${#executables[@]} == 0)); then
  print -u2 "Executable list is empty: $EXECUTABLES_FILE"
  exit 1
fi

alias_block="$(mktemp)"
trap 'rm -f "$alias_block"' EXIT

{
  print -r -- "$START_MARKER"
  print -r -- "# Generated by ${0:t}. Re-run this script to refresh this block."
  print -r -- "# NEMESIS executables automatically mount absolute paths listed in .kls/.lls files."
  print -r -- "nemesis_docker_ext_mount() {"
  print -r -- '    local executable="$1"'
  print -r -- "    shift"
  print
  print -r -- '    local calculation_directory'
  print -r -- '    calculation_directory="$(pwd)"'
  print
  print -r -- '    local -a docker_arguments'
  print -r -- '    docker_arguments=('
  print -r -- '        --rm'
  print -r -- '        -i'
  print -r -- '        -v "$calculation_directory:/data"'
  print -r -- '        -w /data'
  print -r -- '    )'
  print
  print -r -- '    local -a list_files'
  print -r -- '    local candidate'
  print -r -- '    for candidate in "$calculation_directory"/*.kls(N) "$calculation_directory"/*.lls(N); do'
  print -r -- '        case "$(basename "$candidate")" in'
  print -r -- '            intrad.kls|intrad.lls) ;;'
  print -r -- '            *) list_files+=("$candidate") ;;'
  print -r -- '        esac'
  print -r -- '    done'
  print
  print -r -- '    if (( ${#list_files[@]} > 1 )); then'
  print -r -- '        print -u2 "Error: found more than one .kls/.lls file in $calculation_directory"'
  print -r -- '        print -u2 "       ${list_files[*]}"'
  print -r -- '        return 2'
  print -r -- '    fi'
  print
  print -r -- '    typeset -A mounted_directories'
  print -r -- '    if (( ${#list_files[@]} == 1 )); then'
  print -r -- '        local list_file="${list_files[1]}" line external_file external_directory'
  print -r -- '        while IFS= read -r line || [[ -n "$line" ]]; do'
  print -r -- '            line="${line#"${line%%[![:space:]]*}"}"'
  print -r -- '            line="${line%"${line##*[![:space:]]}"}"'
  print -r -- '            [[ -z "$line" || "$line" == \#* ]] && continue'
  print -r -- '            [[ "$line" != /* ]] && continue'
  print
  print -r -- '            external_file="$line"'
  print -r -- '            external_directory="$(dirname "$external_file")"'
  print -r -- '            if [[ ! -e "$external_file" ]]; then'
  print -r -- '                print -u2 "Error: external file does not exist on the host:"'
  print -r -- '                print -u2 "       $external_file"'
  print -r -- '                return 2'
  print -r -- '            fi'
  print
  print -r -- '            if [[ -z "${mounted_directories[$external_directory]}" ]]; then'
  print -r -- '                print -u2 "Mounting external data directory: $external_directory"'
  print -r -- '                docker_arguments+=(--mount "type=bind,source=$external_directory,target=$external_directory,readonly")'
  print -r -- '                mounted_directories[$external_directory]=1'
  print -r -- '            fi'
  print -r -- '        done < "$list_file"'
  print -r -- '    fi'
  print
  print -r -- '    command docker run "${docker_arguments[@]}"' \
    "        $IMAGE_NAME" '"$executable" "$@"'
  print -r -- '}'
  print
  print -r -- "nemesis_docker() {"
  print -r -- '    local executable="$1"'
  print -r -- '    shift'
  print -r -- '    command docker run --rm -i -v "$(pwd)":/data -w /data' \
    "$IMAGE_NAME" '"$executable" "$@"'
  print -r -- '}'
  print
  for executable in "${executables[@]}"; do
    if [[ "$executable" == Nemesis* ]]; then
      print -r -- "alias $executable='nemesis_docker_ext_mount $executable'"
    else
      print -r -- "alias $executable='nemesis_docker $executable'"
    fi
  done
  print -r -- "$END_MARKER"
} > "$alias_block"

touch "$ZSHRC_FILE"

if grep -Fq "$START_MARKER" "$ZSHRC_FILE"; then
  awk -v start="$START_MARKER" -v end="$END_MARKER" '
    $0 == start { skipping = 1; next }
    $0 == end { skipping = 0; next }
    !skipping { print }
  ' "$ZSHRC_FILE" > "${ZSHRC_FILE}.tmp"
  mv "${ZSHRC_FILE}.tmp" "$ZSHRC_FILE"
fi

{
  print
  cat "$alias_block"
} >> "$ZSHRC_FILE"

print -r -- "Added ${#executables[@]} NEMESIS Docker aliases to $ZSHRC_FILE"
print -r -- "Reload with: source $ZSHRC_FILE"
