#!/usr/bin/env bash
set -euo pipefail

BASHRC_FILE="${1:-$HOME/.bashrc}"
IMAGE_NAME="${NEMESIS_DOCKER_IMAGE:-nemesis-app}"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
EXECUTABLES_FILE="${NEMESIS_EXECUTABLES_FILE:-$SCRIPT_DIR/nemesis_executables.txt}"
START_MARKER="# >>> NEMESIS docker aliases >>>"
END_MARKER="# <<< NEMESIS docker aliases <<<"

if [[ ! -f "$EXECUTABLES_FILE" ]]; then
  printf 'Executable list not found: %s\n' "$EXECUTABLES_FILE" >&2
  exit 1
fi

executables=()
while IFS= read -r executable; do
  executable="${executable#"${executable%%[![:space:]]*}"}"
  executable="${executable%"${executable##*[![:space:]]}"}"

  if [[ -z "$executable" || "$executable" == \#* ]]; then
    continue
  fi

  executables+=("$executable")
done < "$EXECUTABLES_FILE"

if ((${#executables[@]} == 0)); then
  printf 'Executable list is empty: %s\n' "$EXECUTABLES_FILE" >&2
  exit 1
fi

alias_block="$(mktemp)"
trap 'rm -f "$alias_block"' EXIT

{
  printf '%s\n' "$START_MARKER"
  printf '# Generated by %s. Re-run this script to refresh this block.\n' "$(basename "$0")"
  for executable in "${executables[@]}"; do
    printf "alias %s='docker run --rm -i -v \"\$(pwd)\":/data -w /data %s %s'\n" \
      "$executable" "$IMAGE_NAME" "$executable"
  done
  printf '%s\n' "$END_MARKER"
} > "$alias_block"

touch "$BASHRC_FILE"

if grep -Fq "$START_MARKER" "$BASHRC_FILE"; then
  awk -v start="$START_MARKER" -v end="$END_MARKER" '
    $0 == start { skipping = 1; next }
    $0 == end { skipping = 0; next }
    !skipping { print }
  ' "$BASHRC_FILE" > "${BASHRC_FILE}.tmp"
  mv "${BASHRC_FILE}.tmp" "$BASHRC_FILE"
fi

{
  printf '\n'
  cat "$alias_block"
} >> "$BASHRC_FILE"

printf 'Added %d NEMESIS Docker aliases to %s\n' "${#executables[@]}" "$BASHRC_FILE"
printf 'Reload with: source %s\n' "$BASHRC_FILE"
