#!/usr/bin/env bash
set -euo pipefail

BASHRC_FILE="${1:-$HOME/.bashrc}"
IMAGE_NAME="${NEMESIS_DOCKER_IMAGE:-patrickirwinoxford/docker_nemesis}"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
EXECUTABLES_FILE="${NEMESIS_EXECUTABLES_FILE:-$SCRIPT_DIR/nemesis_executables.txt}"
START_MARKER="# >>> NEMESIS docker aliases >>>"
END_MARKER="# <<< NEMESIS docker aliases <<<"

if [[ ! -f "$EXECUTABLES_FILE" ]]; then
  printf 'Executable list not found: %s\n' "$EXECUTABLES_FILE" >&2
  exit 1
fi

executables=()
while IFS= read -r executable; do
  executable="${executable#"${executable%%[![:space:]]*}"}"
  executable="${executable%"${executable##*[![:space:]]}"}"

  if [[ -z "$executable" || "$executable" == \#* ]]; then
    continue
  fi

  executables+=("$executable")
done < "$EXECUTABLES_FILE"

if ((${#executables[@]} == 0)); then
  printf 'Executable list is empty: %s\n' "$EXECUTABLES_FILE" >&2
  exit 1
fi

alias_block="$(mktemp)"
trap 'rm -f "$alias_block"' EXIT

{
  printf '%s\n' "$START_MARKER"
  printf '# Generated by %s. Re-run this script to refresh this block.\n' "$(basename "$0")"
  printf 'nemesis_docker_image=%q\n' "$IMAGE_NAME"
  cat <<'FUNCTIONS'
# NEMESIS executables automatically mount absolute paths listed in .kls/.lls files.
nemesis_docker() {
    local executable="$1"
    shift

    local calculation_directory
    calculation_directory="$(pwd)"

    local -a docker_arguments=(
        --rm
        -i
        -v "$calculation_directory:/data"
        -w /data
    )
    local -a list_files=()
    local candidate
    for candidate in "$calculation_directory"/*.kls "$calculation_directory"/*.lls; do
        [[ -e "$candidate" ]] || continue
        case "$(basename "$candidate")" in
            intrad.kls|intrad.lls) ;;
            *) list_files+=("$candidate") ;;
        esac
    done

    if (( ${#list_files[@]} > 1 )); then
        printf 'Error: found more than one .kls/.lls file in %s\n' "$calculation_directory" >&2
        printf '       %s\n' "${list_files[*]}" >&2
        return 2
    fi

    local -A mounted_directories=()
    if (( ${#list_files[@]} == 1 )); then
        local list_file="${list_files[0]}" line external_file external_directory
        while IFS= read -r line || [[ -n "$line" ]]; do
            line="${line#"${line%%[![:space:]]*}"}"
            line="${line%"${line##*[![:space:]]}"}"
            [[ -z "$line" || "$line" == \#* || "$line" != /* ]] && continue

            external_file="$line"
            external_directory="$(dirname "$external_file")"
            if [[ ! -e "$external_file" ]]; then
                printf 'Error: external file does not exist on the host:\n       %s\n' "$external_file" >&2
                return 2
            fi

            if [[ -z "${mounted_directories[$external_directory]+x}" ]]; then
                printf 'Mounting external data directory: %s\n' "$external_directory" >&2
                docker_arguments+=(--mount "type=bind,source=$external_directory,target=$external_directory,readonly")
                mounted_directories[$external_directory]=1
            fi
        done < "$list_file"
    fi

    command docker run "${docker_arguments[@]}" "$nemesis_docker_image" "$executable" "$@"
}

nemesis_docker_run() {
    local executable="$1"
    shift
    command docker run --rm -i -v "$(pwd)":/data -w /data "$nemesis_docker_image" "$executable" "$@"
}
FUNCTIONS
  for executable in "${executables[@]}"; do
    if [[ "$executable" == Nemesis* ]]; then
      printf "alias %s='nemesis_docker %s'\n" "$executable" "$executable"
    else
      printf "alias %s='nemesis_docker_run %s'\n" "$executable" "$executable"
    fi
  done
  printf '%s\n' "$END_MARKER"
} > "$alias_block"

touch "$BASHRC_FILE"

if grep -Fq "$START_MARKER" "$BASHRC_FILE"; then
  awk -v start="$START_MARKER" -v end="$END_MARKER" '
    $0 == start { skipping = 1; next }
    $0 == end { skipping = 0; next }
    !skipping { print }
  ' "$BASHRC_FILE" > "${BASHRC_FILE}.tmp"
  mv "${BASHRC_FILE}.tmp" "$BASHRC_FILE"
fi

{
  printf '\n'
  cat "$alias_block"
} >> "$BASHRC_FILE"

printf 'Added %d NEMESIS Docker aliases to %s\n' "${#executables[@]}" "$BASHRC_FILE"
printf 'Reload with: source %s\n' "$BASHRC_FILE"
