#!/usr/bin/env zsh
set -euo pipefail

ZSHRC_FILE="${1:-$HOME/.zshrc}"
IMAGE_NAME="${NEMESIS_DOCKER_IMAGE:-patrickirwinoxford/docker_nemesis}"
SCRIPT_DIR="${0:A:h}"
EXECUTABLES_FILE="${NEMESIS_EXECUTABLES_FILE:-$SCRIPT_DIR/nemesis_executables.txt}"
START_MARKER="# >>> NEMESIS docker aliases >>>"
END_MARKER="# <<< NEMESIS docker aliases <<<"

if [[ ! -f "$EXECUTABLES_FILE" ]]; then
  print -u2 "Executable list not found: $EXECUTABLES_FILE"
  exit 1
fi

executables=()
while IFS= read -r executable; do
  executable="${executable#"${executable%%[![:space:]]*}"}"
  executable="${executable%"${executable##*[![:space:]]}"}"

  if [[ -z "$executable" || "$executable" == \#* ]]; then
    continue
  fi

  executables+=("$executable")
done < "$EXECUTABLES_FILE"

if ((${#executables[@]} == 0)); then
  print -u2 "Executable list is empty: $EXECUTABLES_FILE"
  exit 1
fi

alias_block="$(mktemp)"
trap 'rm -f "$alias_block"' EXIT

{
  print -r -- "$START_MARKER"
  print -r -- "# Generated by ${0:t}. Re-run this script to refresh this block."
  for executable in "${executables[@]}"; do
    print -r -- "alias $executable='docker run --rm -i -v \"\$(pwd)\":/data -w /data $IMAGE_NAME $executable'"
  done
  print -r -- "$END_MARKER"
} > "$alias_block"

touch "$ZSHRC_FILE"

if grep -Fq "$START_MARKER" "$ZSHRC_FILE"; then
  awk -v start="$START_MARKER" -v end="$END_MARKER" '
    $0 == start { skipping = 1; next }
    $0 == end { skipping = 0; next }
    !skipping { print }
  ' "$ZSHRC_FILE" > "${ZSHRC_FILE}.tmp"
  mv "${ZSHRC_FILE}.tmp" "$ZSHRC_FILE"
fi

{
  print
  cat "$alias_block"
} >> "$ZSHRC_FILE"

print -r -- "Added ${#executables[@]} NEMESIS Docker aliases to $ZSHRC_FILE"
print -r -- "Reload with: source $ZSHRC_FILE"
